services:
  web:
    build: .
    command: gunicorn appvalidador.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17.5
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/opt/validador-itens/staticfiles
      - media:/opt/validador-itens/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/app/staticfiles
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/app/staticfiles 
      --email wsoares@exploratoriadigital.com.br --agree-tos --no-eff-email 
      -d validacaoitens.com -d www.validacaoitens.com"

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
  staticfiles:
  media:



